### PR TITLE
Provide the total size up front when installing all tools (zopen install --all)

### PR DESCRIPTION
**Pull request by IgorTodorovskiIBM**
Output as of today:
```
You have chosen to install all tools. An estimated 2819.17 MB of additional disk space will be used.
```

### CODE REVIEW

**Review by DevonianTeuchter — COMMENTED** [review]
LGTM as-is but would a 'du' space check be a useful addition at this point to save failure during the install if insufficient space?

**Review by MikeFultonDev — APPROVED** [review]
LGTM - if you haven't already, do you want to open an issue to handle the size calculation for a set of packages (as opposed to all)?

**Comment by MikeFultonDev** [comment]
i like that. i also think if there is less than XX MB in the file system, we should just fail too... If it's close enough to empty, they should clean up.

**Comment by IgorTodorovskiIBM** [comment]
I like the idea as well! However, I think some filesystems are set up such that they can grow once they reach the max quota. Should we always emit an error? For now I've added it as a warning.

```
You have chosen to install all tools. An estimated 2840 MB of additional disk space will be used.
***WARNING: Your zopen file-system (/home/itodoro/zopen) only has 260 MB of available space.
Enter 'all' to confirm full installation [takes a long time so be sure!]:
```

**Comment by DevonianTeuchter** [comment]
> I like the idea as well! However, I think some filesystems are set up such that they can grow once they reach the max quota. Should we always emit an error? For now I've added it as a warning.
> 
> ```
> You have chosen to install all tools. An estimated 2840 MB of additional disk space will be used.
> ***WARNING: Your zopen file-system (/home/itodoro/zopen) only has 260 MB of available space.
> Enter 'all' to confirm full installation [takes a long time so be sure!]:
> ```
LGTM - A warning seems reasonable - we've advised them, they can answer no and if they still proceed then that's on them - and like you say, some filesystems can dynamically resize.

**Review by DevonianTeuchter — APPROVED** [review]

**Pull request merged**
