### PR TITLE
Add vim-fugitive and revise vim-gitgutter

### PR DESCRIPTION
**Pull request by ijmitch**

### CODE REVIEW

**Review by DevonianTeuchter — CHANGES_REQUESTED** [review]
"Its README" is missing an apostrophe

Otherwise LGTM.
Good to know that the plugin ecosystem works on z/OS

**Comment by ijmitch** [comment]
>"Its README" is missing an apostrophe

eh-hem... no it's not - this is the possessive and not the contraction of "it is". As the husband of a former IBM editor, I've been schooled in this too many times! 

But also https://editorsmanual.com/articles/apostrophe-in-its/ .

**Comment by DevonianTeuchter** [comment]
> >"Its README" is missing an apostrophe
> 
> eh-hem... no it's not - this is the possessive and not the contraction of "it is". As the husband of a former IBM editor, I've been schooled in this too many times! 
> 
> But also https://editorsmanual.com/articles/apostrophe-in-its/ .

Yeah, was thinking its'  rather than it's but realise the error of my ways 😁

**Review by DevonianTeuchter — APPROVED** [review]
LGTM 😁

**Pull request merged**
