### PR TITLE
Add bump and build_and_test yml files to data dir (used by zopen generate)

### PR DESCRIPTION
**Pull request by IgorTodorovskiIBM**
Add build_and_test.yml and bump.yml so that they can be copied into the project directory via zopen generate

### CODE REVIEW

**Comment by IgorTodorovskiIBM** [comment]
> * actions/checkout

Good catch, FYI @v1gnesh

**Comment by v1gnesh** [comment]
> > * actions/checkout
> 
> Good catch, FYI @v1gnesh

I'll create new ones with @main.
For the ones that exist already, is it possible for you to bulk push an update changing master to main please..
I'd have to open a PR whereas I think you can push directly :)

**Comment by IgorTodorovskiIBM** [comment]
> > > * actions/checkout
> > 
> > 
> > Good catch, FYI @v1gnesh
> 
> I'll create new ones with @main. For the ones that exist already, is it possible for you to bulk push an update changing master to main please.. I'd have to open a PR whereas I think you can push directly :)

Yep, I can do a bulk update

**Review by MikeFultonDev — APPROVED** [review]
LGTM

**Pull request merged**
