### PR TITLE
Add reuseable github action workflow for testing ports

### PR DESCRIPTION
**Pull request by IgorTodorovskiIBM**
The BuildAndTest workflow will trigger a build on a PR
* it triggers a jenkins job on the z/OS side and retrieves the result and also creates a status check.

BuildAndTest is a reusable github workflow, the idea is that BuildAndTest can be reused by every port repository for triggering builds..

In the case of meta:
* jenkins-test.yml calls the BuildAndTest to trigger a build on the meta repo.

Documentation added to contributing guide: https://github.com/ZOSOpenTools/meta/pull/484/files#diff-eca12c0a30e25b4b46522ebf89465a03ba72a03f540796c979137931d8f92055

### CODE REVIEW

**Review by MikeFultonDev — COMMENTED** [review]
can you add a doc section somewhere so people know how to use it?

**Comment by IgorTodorovskiIBM** [comment]
> can you add a doc section somewhere so people know how to use it?

Yep, that's a good idea. My plan is to add the github action to zopen-generate and also to add it to all existing ports.

**Comment by IgorTodorovskiIBM** [comment]
Add some documentation to the contributing guidelines doc and added logic to zopen-generate to copy the workflow

**Review by MikeFultonDev — APPROVED** [review]
Lgtm

**Pull request merged**
