### PR TITLE
Update GitOnZOS.md

### PR DESCRIPTION
**Pull request by ijmitch**
The announcement specifically mentions v2.39.1 but we're way beyond that now.

I've suggested some wording, but not even sure it deserves the prominence it has anymore and it could just be a note further down?

### CODE REVIEW

**Comment by ijmitch** [comment]
There's a few approved PRs waiting to be merged... who has the ball?

**Comment by MikeFultonDev** [comment]
Hi

Once approved you can merge

**Comment by ijmitch** [comment]
well.... not without write access I can't:

image

**Comment by MikeFultonDev** [comment]
@IgorTodorovskiIBM or I can you give you authority tomorrow. No computer right now

**Comment by ijmitch** [comment]
Thanks @IgorTodorovskiIBM ... once I accepted the invitation to collaborate all was good.

**Pull request merged**
