### PR TITLE
Add copyright text

### PR DESCRIPTION
**Pull request by AnthonyGiorgio**
This PR adds a copyright line to each script file.    It also sorts the command line arguments alphabetically for some of the scripts.  Finally, it continues to speed up help text printing by replacing repeated `echo` calls with a single `cat`.

### CODE REVIEW

**Review by MikeFultonDev — COMMENTED** [review]
Can you elaborate on the value of a copyright for open source?

**Comment by AnthonyGiorgio** [comment]
> Can you elaborate on the value of a copyright for open source?

IP law is complicated and varied in different countries.  In the US, the code is automatically copyrighted upon being written, so having a statement like that at least makes the authorship clear.

 Having a copyright statement is pretty standard for open source projects - take a look at this [example from less](https://github.com/gwsw/less/blob/8f4691901c98aef748e48837650f9c847d0236b5/main.c#L2).

**Comment by IgorTodorovskiIBM** [comment]
Changes look good overall.

Should the copyright start from the first date of publication? 2022?

Also, I'm noticing that copyright notices are less common in newer open source projects. I found this article which attempts to explain why it's no longer as valuable: https://opensource.com/article/20/10/copyright-notices-open-source-software

**Comment by AnthonyGiorgio** [comment]
Yes, the date should start with the first date of publication.  Perhaps we could maintain the date(s) in the `zopen-version` file only?

**Comment by MikeFultonDev** [comment]
> Changes look good overall.
> 
> Should the copyright start from the first date of publication? 2022?
> 
> Also, I'm noticing that copyright notices are less common in newer open source projects. I found this article which attempts to explain why it's no longer as valuable: https://opensource.com/article/20/10/copyright-notices-open-source-software

Thanks for the link. I didn’t think there was much value here to start and this seems to reinforce it. 

unless anyone objects I would like to not have copyrights in the code the z/OS open tools community merges. I will clean up the generic copyright I put in before which I feel now was a mistake. 
we should not change any of the licenses even if those do have some copyright text - we need to leave those as js.

**Review by MikeFultonDev — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
