### PR TITLE
Tag and encode .env as IBM-1047

### PR DESCRIPTION
**Pull request by IgorTodorovskiIBM**
The .env is the entry point for any consumer/developer and as such, should be encoded in the default encoding (IBM-1047). This way we can also add the required auto-conversion environment variables

### CODE REVIEW

**Review by MikeFultonDev — COMMENTED** [review]
Looks good. Since this is a very special marking of IBM-1047 for people sourc'ing from
a dubious shell, do you want to add a comment to that effect to indicate this is why you mark
it 1047?

**Review by MikeFultonDev — APPROVED** [review]
Lgtm

**Comment by IgorTodorovskiIBM** [comment]
> Looks good. Since this is a very special marking of IBM-1047 for people sourc'ing from a dubious shell, do you want to add a comment to that effect to indicate this is why you mark it 1047?

Added a comment, thanks

**Review by MikeFultonDev — APPROVED** [review]
LGTM

**Pull request merged**
