### PR TITLE
Create codeql.yml

### PR DESCRIPTION
**Pull request by IgorTodorovskiIBM**
Enable codeql scanning, will try it on meta first

### CODE REVIEW

**Comment by MikeFultonDev** [comment]
can you provide a little info on what it's doing? what types of scans?

**Review by MikeFultonDev — COMMENTED** [review]
.

**Comment by IgorTodorovskiIBM** [comment]
Hey Mike, it's a security code scanning tool - more info here: https://codeql.github.com/

The one issue right now is that is uses the file extensions to determine the file type. So our .patch files would not be analyzed.

**Comment by MikeFultonDev** [comment]
Hm. That’s too bad. Maybe we should put patch. At the front? Support both styles for search write a script to switch it all, then change the pattern? Back burner item…

**Comment by IgorTodorovskiIBM** [comment]
> Is there a way to say that files with no extension could be a script and to look in the first line (eg buildenv)

Looks like the code needs to be buildable - https://stackoverflow.com/questions/62105456/how-can-i-use-codeql-on-partial-c-source-code.

**Comment by IgorTodorovskiIBM** [comment]
I'll close this for now, we'll need a github action that clones the source and runs the static scanning.

**Pull request closed without merging**
