### PR TITLE
Add in check for _BPXK_AUTOCVT and set if not set (fail if set to OFF)

### PR DESCRIPTION
**Pull request by MikeFultonDev**
Ran metaport manually. All good:
```
- Integration complete
- Sourcing environment to run any setup
Setting up meta...
Setup completed.
```

### CODE REVIEW

**Review by IgorTodorovskiIBM — APPROVED** [review]
LGTM

**Review by DevonianTeuchter — APPROVED** [review]
LGTM - minor nit that there's a missing full-stop at the end of the message that some folks might like :-)

**Comment by MikeFultonDev** [comment]
> LGTM - minor nit that there's a missing full-stop at the end of the message that some folks might like :-)

ah! sorry - didn't see this until now. will fix.

**Pull request merged**
