### PR TITLE
Contributing FIXENV

### PR DESCRIPTION
**Pull request by lbdyck**
Utility to help remount, move, or copy the zot installation.

### CODE REVIEW

**Review by MikeFultonDev — COMMENTED** [review]
can you add support for a -h and/or -? option so people can see what it does?

what about names instead of numbers to describe what the tool does?

instead of 'fixenv' how about 'genprofile' or something more descriprive?

**Review by MikeFultonDev — APPROVED** [review]
Lgtm. One thing to consider is how this may need to be modified when the improved install support comes out.

**Comment by lbdyck** [comment]
it's possible this won't be needed at that point.

**Comment by IgorTodorovskiIBM** [comment]
@lbdyck , with the new zopen-config, are you still having to use FIXENV or is zopen-config sufficient now?

**Comment by lbdyck** [comment]
if you are referring to .../etc/zopen-config then that does not satisfy - what I need, for use with ZIGI, is either a quick process, which this isn't, or an environment file similar to this:

```
ZOPEN_ROOTFS=/u/lbdyck/zopen                                                                                 
ZOPEN_LOG_PATH=/u/lbdyck/zopen/var/log                                                                       
LIBICONV_HOME=/u/lbdyck/zopen/usr/local/zopen/libiconv/libiconv-1.17.20230831_134536.zos                     
LESS_HOME=/u/lbdyck/zopen/usr/local/zopen/less/less-643.20230909_075924.zos                                  
LIBPATH=/u/lbdyck/zopen/usr/lib:/usr/local/ro202302/envs/cbt/lib:/usr/local/ro202302/envs/cbt/lib/perl5/5.32....
PERL5_HOME=/u/lbdyck/zopen/usr/local/zopen/perl/perl5-blead.20230605_161457.zos                              
MAN_TEST_DISABLE_SYSTEM_CONFIG=1                                                                             
GROFF_TYPESETTER=utf8                                                                                        
GIT_TEMPLATE_DIR=/u/lbdyck/zopen/usr/local/zopen/git/git-2.41.0.20230923_021248.zos/share/git-core/templates 
ASCII_TERMINFO=/u/lbdyck/zopen/usr/local/zopen/ncurses/ncurses-6.3.20230914_231534.zos/share/terminfo/       
```

**Comment by lbdyck** [comment]
in other words - something quick that doesn't require processing.

**Pull request closed without merging**
